Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -28,9 +28,9 @@ jobs:
             exit 1
           fi
 
-          # Print the JWT for debugging (mask the value!)
+          # Print the JWT for debugging (DO NOT COMMIT THIS CHANGE!)
           echo "GitHub Actions JWT: $TOKEN"
-          echo "::add-mask::$TOKEN"
+          #echo "::add-mask::$TOKEN"  # Temporarily disable masking
 
           # Authenticate to Conjur Cloud
           CONJUR_AUTH_RESPONSE=$(curl -vvvk --request POST https://lvm-uat.secretsmgr.cyberark.cloud/api/authn-jwt/lvmtest/conjur/host%2Fdata%2Fjwtwork/authenticate --header "Content-Type:application/x-www-form-urlencoded" --data-urlencode jwt="$TOKEN")
@@ -46,14 +46,14 @@ jobs:
 
           export shortLiveToken="$shortLiveToken"
 
-          # Retrieve secret from Conjur Cloud
-          SECRET=$(curl -vvvk --request GET https://lvm-uat.secretsmgr.cyberark.cloud/api/secrets/conjur/variable/data%2Fvault%2FTest_VCP%2FApplication-ConjurPass-conjurtestvar3%2Fpassword -H "Authorization: Bearer $shortLiveToken") # DOUBLE CHECK THIS HEADER
-          if [ $? -ne 0 ]; then
-            echo "Error retrieving secret"
-            echo "Check the Authorization header format and the shortLiveToken value."
-            exit 1
-          fi
+          # Retrieve secret from Conjur Cloud (COMMENTED OUT FOR NOW)
+          #SECRET=$(curl -vvvk --request GET https://lvm-uat.secretsmgr.cyberark.cloud/api/secrets/conjur/variable/data%2Fvault%2FTest_VCP%2FApplication-ConjurPass-conjurtestvar3%2Fpassword -H "Authorization: Bearer $shortLiveToken") # DOUBLE CHECK THIS HEADER
+          #if [ $? -ne 0 ]; then
+          #  echo "Error retrieving secret"
+          #  echo "Check the Authorization header format and the shortLiveToken value."
+          #  exit 1
+          #fi
 
-          echo "::add-mask::$SECRET"
-          echo "$SECRET" > secret.txt
-          echo "Secret written to secret.txt (but is masked in output)"
+          #echo "::add-mask::$SECRET"
+          #echo "$SECRET" > secret.txt
+          #echo "Secret written to secret.txt (but is masked in output)"
